// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OT.Data;

#nullable disable

namespace OT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260709150554_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OT.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Koleksi anggur berkualitas tinggi dengan fermentasi sempurna.",
                            Name = "Wine"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minuman spirit murni yang disuling untuk mencapai kehalusan paripurna.",
                            Name = "Spirits"
                        });
                });

            modelBuilder.Entity("OT.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("ABV_Percentage")
                        .HasColumnType("real");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ABV_Percentage = 14.7f,
                            CategoryId = 1,
                            Description = "Anggur Merah dengan sentuhan rempah eksotis, memberikan profil rasa klasik yang menghangatkan.",
                            ImageUrl = "/OT-Product/webp/amer.webp",
                            Name = "Anggur Merah",
                            Price = 75000.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ABV_Percentage = 40f,
                            CategoryId = 2,
                            Description = "Vodka murni dengan distilasi 3 kali. Terinspirasi dari kejernihan es glasial, memberikan kehalusan ekstra pada setiap tegukan.",
                            ImageUrl = "/OT-Product/webp/iceland.webp",
                            Name = "Iceland Vodka",
                            Price = 120000.00m,
                            Stock = 150
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ABV_Percentage = 43f,
                            CategoryId = 2,
                            Description = "Whisky bernuansa lokal dengan kedalaman rasa ek yang dipanggang (toasted oak) dan aroma karamel yang kaya.",
                            ImageUrl = "/OT-Product/webp/batavia.webp",
                            Name = "Batavia Whisky",
                            Price = 150000.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ABV_Percentage = 38f,
                            CategoryId = 2,
                            Description = "Tequila premium yang difermentasi dari agave biru pilihan. Memberikan keseimbangan sempurna antara rasa manis dan pedas lada.",
                            ImageUrl = "/OT-Product/webp/codingo.webp",
                            Name = "Codigo Tequila",
                            Price = 850000.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ABV_Percentage = 40f,
                            CategoryId = 2,
                            Description = "Pilihan klasik bagi penikmat tequila sejati. Menawarkan jejak aroma citrus dan agave panggang yang intens.",
                            ImageUrl = "/OT-Product/webp/blueagave.webp",
                            Name = "Jose Cuervo",
                            Price = 650000.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            ABV_Percentage = 12f,
                            CategoryId = 1,
                            Description = "Minuman anggur dengan dominasi rasa blackcurrant segar. Cocok dinikmati dingin dalam suasana santai.",
                            ImageUrl = "/OT-Product/webp/api.webp",
                            Name = "API Blackcurrant",
                            Price = 90000.00m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            ABV_Percentage = 35f,
                            CategoryId = 2,
                            Description = "Rum aromatik yang dipadukan dengan rempah tropis. Memiliki karakter rasa manis, hangat, dan kompleks.",
                            ImageUrl = "/OT-Product/webp/mantaa.webp",
                            Name = "Manta Spiced",
                            Price = 110000.00m,
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            ABV_Percentage = 40f,
                            CategoryId = 2,
                            Description = "Varian eksklusif dengan sentuhan warna keemasan dan profil rasa yang kaya akan nuansa vanila dan madu.",
                            ImageUrl = "/OT-Product/webp/mazemaze.webp",
                            Name = "Maze Maze Gold",
                            Price = 135000.00m,
                            Stock = 90
                        });
                });

            modelBuilder.Entity("OT.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OT.Models.Product", b =>
                {
                    b.HasOne("OT.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OT.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
