// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OT.Data;

#nullable disable

namespace OT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OT.Models.ItemKeranjang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kuantitas")
                        .HasColumnType("integer");

                    b.Property<Guid>("PenggunaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdukId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("ProdukId");

                    b.ToTable("ItemKeranjang");
                });

            modelBuilder.Entity("OT.Models.ItemPesanan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kuantitas")
                        .HasColumnType("integer");

                    b.Property<Guid>("PesananId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdukId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PesananId");

                    b.HasIndex("ProdukId");

                    b.ToTable("ItemPesanan");
                });

            modelBuilder.Entity("OT.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deskripsi = "Minuman beralkohol hasil proses distilasi.",
                            NamaKategori = "Spirits"
                        },
                        new
                        {
                            Id = 2,
                            Deskripsi = "Anggur dan minuman fermentasi warisan Nusantara.",
                            NamaKategori = "Wine & Minuman Tradisional"
                        });
                });

            modelBuilder.Entity("OT.Models.Pengguna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("KataSandiHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NamaPengguna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Peran")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PoinLoyalitas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TingkatMember")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Pengguna");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "julioal1@otgroup.me",
                            KataSandiHash = "AQAAAAIAAYagAAAAEFIX4XgXhajVoJrYcweFqMqmxkIgN/7DKGTumSLD4tYLD1OyyYxTkszP6KBx42YZjA==",
                            NamaLengkap = "Julio Alfredo",
                            NamaPengguna = "JulioAlfredo1",
                            Peran = "Admin",
                            PoinLoyalitas = 9999,
                            TanggalLahir = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TingkatMember = "Platinum"
                        });
                });

            modelBuilder.Entity("OT.Models.Pesanan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NomorSeriTransaksi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PenggunaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PoinDiperoleh")
                        .HasColumnType("integer");

                    b.Property<decimal>("PotonganHarga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatusPembayaran")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TanggalPesanan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId");

                    b.ToTable("Pesanan");
                });

            modelBuilder.Entity("OT.Models.Produk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImbalanPoin")
                        .HasColumnType("integer");

                    b.Property<string>("JalurGambar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<string>("KodeSKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("PersentaseAlkohol")
                        .HasColumnType("real");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.Property<int>("VolumeML")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Deskripsi = "Anggur merah legendaris warisan leluhur.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 75000.00m,
                            ImbalanPoin = 10,
                            JalurGambar = "/assets/produk/amer.webp",
                            KategoriId = 2,
                            KodeSKU = "WNE-AMER-001",
                            NamaProduk = "OT Anggur Merah",
                            PersentaseAlkohol = 14.7f,
                            Stok = 500,
                            VolumeML = 620
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Deskripsi = "Vodka murni dengan tiga kali proses distilasi untuk kelembutan ekstra.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 250000.00m,
                            ImbalanPoin = 50,
                            JalurGambar = "/assets/produk/iceland.webp",
                            KategoriId = 1,
                            KodeSKU = "SPR-ICE-001",
                            NamaProduk = "Iceland Triple Distilled Vodka",
                            PersentaseAlkohol = 40f,
                            Stok = 300,
                            VolumeML = 700
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Deskripsi = "Whisky blend premium dengan karakter khas Batavia yang kuat namun elegan.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 320000.00m,
                            ImbalanPoin = 60,
                            JalurGambar = "/assets/produk/batavia.webp",
                            KategoriId = 1,
                            KodeSKU = "SPR-BTV-001",
                            NamaProduk = "Batavia Blended Whisky",
                            PersentaseAlkohol = 43f,
                            Stok = 200,
                            VolumeML = 700
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Deskripsi = "Tequila Añejo ultra-premium yang dimatangkan sempurna di tong Cabernet tua.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 1500000.00m,
                            ImbalanPoin = 300,
                            JalurGambar = "/assets/produk/codingo.webp",
                            KategoriId = 1,
                            KodeSKU = "SPR-COD-001",
                            NamaProduk = "Código 1530 Añejo Tequila",
                            PersentaseAlkohol = 40f,
                            Stok = 50,
                            VolumeML = 750
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            Deskripsi = "Tequila klasik dunia yang diracik dari tanaman blue agave pilihan terbaik.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 450000.00m,
                            ImbalanPoin = 90,
                            JalurGambar = "/assets/produk/blueagave.webp",
                            KategoriId = 1,
                            KodeSKU = "SPR-JCB-001",
                            NamaProduk = "Jose Cuervo Especial Blue Agave",
                            PersentaseAlkohol = 38f,
                            Stok = 150,
                            VolumeML = 750
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            Deskripsi = "Minuman anggur modern dengan paduan rasa blackcurrant yang intens dan berani.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 85000.00m,
                            ImbalanPoin = 15,
                            JalurGambar = "/assets/produk/api.webp",
                            KategoriId = 2,
                            KodeSKU = "WNE-API-001",
                            NamaProduk = "API Anggur Blackcurrant",
                            PersentaseAlkohol = 19.7f,
                            Stok = 400,
                            VolumeML = 620
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            Deskripsi = "Rum rempah keemasan dengan sensasi karamel manis yang hangat di setiap tegukan.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 210000.00m,
                            ImbalanPoin = 40,
                            JalurGambar = "/assets/produk/mantaa.webp",
                            KategoriId = 1,
                            KodeSKU = "SPR-MNT-001",
                            NamaProduk = "Manta Original Spiced Gold",
                            PersentaseAlkohol = 35f,
                            Stok = 250,
                            VolumeML = 700
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222228"),
                            Deskripsi = "Whisky emas hasil racikan ahli dengan kelembutan yang mudah dinikmati kapan saja.",
                            DibuatPada = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Harga = 180000.00m,
                            ImbalanPoin = 35,
                            JalurGambar = "/assets/produk/mazemaze.webp",
                            KategoriId = 1,
                            KodeSKU = "SPR-MZM-001",
                            NamaProduk = "Maze Maze Gold Whisky",
                            PersentaseAlkohol = 40f,
                            Stok = 350,
                            VolumeML = 700
                        });
                });

            modelBuilder.Entity("OT.Models.ItemKeranjang", b =>
                {
                    b.HasOne("OT.Models.Pengguna", "Pengguna")
                        .WithMany("DaftarItemKeranjang")
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OT.Models.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("OT.Models.ItemPesanan", b =>
                {
                    b.HasOne("OT.Models.Pesanan", "Pesanan")
                        .WithMany("DetailPesanan")
                        .HasForeignKey("PesananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OT.Models.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesanan");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("OT.Models.Pesanan", b =>
                {
                    b.HasOne("OT.Models.Pengguna", "Pengguna")
                        .WithMany("DaftarPesanan")
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("OT.Models.Produk", b =>
                {
                    b.HasOne("OT.Models.Kategori", "Kategori")
                        .WithMany("DaftarProduk")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("OT.Models.Kategori", b =>
                {
                    b.Navigation("DaftarProduk");
                });

            modelBuilder.Entity("OT.Models.Pengguna", b =>
                {
                    b.Navigation("DaftarItemKeranjang");

                    b.Navigation("DaftarPesanan");
                });

            modelBuilder.Entity("OT.Models.Pesanan", b =>
                {
                    b.Navigation("DetailPesanan");
                });
#pragma warning restore 612, 618
        }
    }
}
